// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: transit_pdx.proto

package transit_pdx_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransitPDX_GetScheduledTimes_FullMethodName = "/transitpdx.TransitPDX/GetScheduledTimes"
)

// TransitPDXClient is the client API for TransitPDX service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransitPDXClient interface {
	GetScheduledTimes(ctx context.Context, in *StopId, opts ...grpc.CallOption) (*NextScheduledTimes, error)
}

type transitPDXClient struct {
	cc grpc.ClientConnInterface
}

func NewTransitPDXClient(cc grpc.ClientConnInterface) TransitPDXClient {
	return &transitPDXClient{cc}
}

func (c *transitPDXClient) GetScheduledTimes(ctx context.Context, in *StopId, opts ...grpc.CallOption) (*NextScheduledTimes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextScheduledTimes)
	err := c.cc.Invoke(ctx, TransitPDX_GetScheduledTimes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransitPDXServer is the server API for TransitPDX service.
// All implementations must embed UnimplementedTransitPDXServer
// for forward compatibility.
type TransitPDXServer interface {
	GetScheduledTimes(context.Context, *StopId) (*NextScheduledTimes, error)
	mustEmbedUnimplementedTransitPDXServer()
}

// UnimplementedTransitPDXServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransitPDXServer struct{}

func (UnimplementedTransitPDXServer) GetScheduledTimes(context.Context, *StopId) (*NextScheduledTimes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScheduledTimes not implemented")
}
func (UnimplementedTransitPDXServer) mustEmbedUnimplementedTransitPDXServer() {}
func (UnimplementedTransitPDXServer) testEmbeddedByValue()                    {}

// UnsafeTransitPDXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransitPDXServer will
// result in compilation errors.
type UnsafeTransitPDXServer interface {
	mustEmbedUnimplementedTransitPDXServer()
}

func RegisterTransitPDXServer(s grpc.ServiceRegistrar, srv TransitPDXServer) {
	// If the following call pancis, it indicates UnimplementedTransitPDXServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransitPDX_ServiceDesc, srv)
}

func _TransitPDX_GetScheduledTimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransitPDXServer).GetScheduledTimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransitPDX_GetScheduledTimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransitPDXServer).GetScheduledTimes(ctx, req.(*StopId))
	}
	return interceptor(ctx, in, info, handler)
}

// TransitPDX_ServiceDesc is the grpc.ServiceDesc for TransitPDX service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransitPDX_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transitpdx.TransitPDX",
	HandlerType: (*TransitPDXServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScheduledTimes",
			Handler:    _TransitPDX_GetScheduledTimes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transit_pdx.proto",
}
