// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: transit_pdx.proto

package transit_pdx_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stop_Id int32 `protobuf:"varint,1,opt,name=stop_Id,json=stopId,proto3" json:"stop_Id,omitempty"`
}

func (x *StopId) Reset() {
	*x = StopId{}
	mi := &file_transit_pdx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopId) ProtoMessage() {}

func (x *StopId) ProtoReflect() protoreflect.Message {
	mi := &file_transit_pdx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopId.ProtoReflect.Descriptor instead.
func (*StopId) Descriptor() ([]byte, []int) {
	return file_transit_pdx_proto_rawDescGZIP(), []int{0}
}

func (x *StopId) GetStop_Id() int32 {
	if x != nil {
		return x.Stop_Id
	}
	return 0
}

type NextScheduledTimes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduledTime []int32 `protobuf:"varint,2,rep,packed,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
}

func (x *NextScheduledTimes) Reset() {
	*x = NextScheduledTimes{}
	mi := &file_transit_pdx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextScheduledTimes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextScheduledTimes) ProtoMessage() {}

func (x *NextScheduledTimes) ProtoReflect() protoreflect.Message {
	mi := &file_transit_pdx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextScheduledTimes.ProtoReflect.Descriptor instead.
func (*NextScheduledTimes) Descriptor() ([]byte, []int) {
	return file_transit_pdx_proto_rawDescGZIP(), []int{1}
}

func (x *NextScheduledTimes) GetScheduledTime() []int32 {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

var File_transit_pdx_proto protoreflect.FileDescriptor

var file_transit_pdx_proto_rawDesc = []byte{
	0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x5f, 0x70, 0x64, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x06, 0x53, 0x74, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x6f, 0x70, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x12, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x32, 0x3f, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x50, 0x44,
	0x58, 0x12, 0x31, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x07, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x49, 0x64, 0x1a,
	0x13, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x6e, 0x67, 0x72, 0x6d, 0x6f, 0x75, 0x73, 0x2f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x2d, 0x70, 0x64, 0x78, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transit_pdx_proto_rawDescOnce sync.Once
	file_transit_pdx_proto_rawDescData = file_transit_pdx_proto_rawDesc
)

func file_transit_pdx_proto_rawDescGZIP() []byte {
	file_transit_pdx_proto_rawDescOnce.Do(func() {
		file_transit_pdx_proto_rawDescData = protoimpl.X.CompressGZIP(file_transit_pdx_proto_rawDescData)
	})
	return file_transit_pdx_proto_rawDescData
}

var file_transit_pdx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transit_pdx_proto_goTypes = []any{
	(*StopId)(nil),             // 0: StopId
	(*NextScheduledTimes)(nil), // 1: NextScheduledTimes
}
var file_transit_pdx_proto_depIdxs = []int32{
	0, // 0: TransitPDX.GetScheduledTimes:input_type -> StopId
	1, // 1: TransitPDX.GetScheduledTimes:output_type -> NextScheduledTimes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transit_pdx_proto_init() }
func file_transit_pdx_proto_init() {
	if File_transit_pdx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transit_pdx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transit_pdx_proto_goTypes,
		DependencyIndexes: file_transit_pdx_proto_depIdxs,
		MessageInfos:      file_transit_pdx_proto_msgTypes,
	}.Build()
	File_transit_pdx_proto = out.File
	file_transit_pdx_proto_rawDesc = nil
	file_transit_pdx_proto_goTypes = nil
	file_transit_pdx_proto_depIdxs = nil
}
